use_frameworks!

platform :ios, '9.0'

target 'XFNetworking_Example' do
  pod 'XFNetworking', :path => '../'

  target 'XFNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
